### ISSUE TITLE
刮刮乐报错

### ISSUE THREAD

**Issue by ghost** [po-lan/zhenxun_plugins_TZseries#42]
02-26 19:26:06 [ERROR] nonebot | Running Matcher(type='message', module=extensive_plugin.zhenxun_plugins_TZseries.TZggl) failed.
Traceback (most recent call last):
  File "D:\zhenxun\home\dong\TRSS_Zhenxun\Zhenxun\bot.py", line 21, in <module>
    nonebot.run()
  File "D:\zhenxun\home\dong\TRSS_Zhenxun\home\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-ETT07Wgi-py3.10\lib\site-packages\nonebot\__init__.py", line 273, in run
    get_driver().run(*args, **kwargs)
  File "D:\zhenxun\home\dong\TRSS_Zhenxun\home\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-ETT07Wgi-py3.10\lib\site-packages\nonebot\drivers\fastapi.py", line 172, in run
    uvicorn.run(
  File "D:\zhenxun\home\dong\TRSS_Zhenxun\home\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-ETT07Wgi-py3.10\lib\site-packages\uvicorn\main.py", line 569, in run
    server.run()
  File "D:\zhenxun\home\dong\TRSS_Zhenxun\home\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-ETT07Wgi-py3.10\lib\site-packages\uvicorn\server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "asyncio\runners.py", line 44, in run
ETT07Wgi-py3.10\lib\site-packages\tortoise\queryset.py", line 387, in filter
    return self._filter_or_exclude(negate=False, *args, **kwargs)
  File "D:\zhenxun\home\dong\TRSS_Zhenxun\home\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-ETT07Wgi-py3.10\lib\site-packages\tortoise\queryset.py", line 363, in _filter_or_exclude
    raise TypeError("expected Q objects as args")
TypeError: expected Q objects as args
![CZHAI7PR26DUXK%) KY3SCP](https://user-images.githubusercontent.com/109427426/221407744-e85ed816-67ae-4975-95d3-3b7ddcb73235.png)

**Comment by yuan488** [comment]
同样的报错，请问有解决办法么？

**Comment by ayakasuki** [comment]
+1

**Comment by Starrain08** [comment]
+1

**Comment by 970319835** [comment]
+1
