### ISSUE TITLE
Unknown filter param 'user_qq'

### ISSUE THREAD

**Issue by gili-gili** [po-lan/zhenxun_plugins_TZseries#47]
## Log
```
06-08 13:44:46 [ERROR] nonebot | Running Matcher(type='message', module=extensive_plugin.zhenxun_plugins_TZseries.TZdajie) failed.
Traceback (most recent call last):
  File "/USER_HOME_DIR/zhenxun_bot/bot.py", line 21, in <module>
    nonebot.run()
  File "/USER_HOME_DIR/.cache/pypoetry/virtualenvs/zhenxun-bot-wZ02gYV3-py3.10/lib/python3.10/site-packages/nonebot/__init__.py", line 273, in run
    get_driver().run(*args, **kwargs)
  File "/USER_HOME_DIR/.cache/pypoetry/virtualenvs/zhenxun-bot-wZ02gYV3-py3.10/lib/python3.10/site-packages/nonebot/drivers/fastapi.py", line 172, in run
    uvicorn.run(
  File "/USER_HOME_DIR/.cache/pypoetry/virtualenvs/zhenxun-bot-wZ02gYV3-py3.10/lib/python3.10/site-packages/uvicorn/main.py", line 578, in run
    server.run()
  File "/USER_HOME_DIR/.cache/pypoetry/virtualenvs/zhenxun-bot-wZ02gYV3-py3.10/lib/python3.10/site-packages/uvicorn/server.py", line 61, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/USER_HOME_DIR/.cache/pypoetry/virtualenvs/zhenxun-bot-wZ02gYV3-py3.10/lib/python3.10/site-packages/nonebot/message.py", line 142, in _check_matcher
    await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)
> File "/USER_HOME_DIR/.cache/pypoetry/virtualenvs/zhenxun-bot-wZ02gYV3-py3.10/lib/python3.10/site-packages/nonebot/message.py", line 188, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "/USER_HOME_DIR/.cache/pypoetry/virtualenvs/zhenxun-bot-wZ02gYV3-py3.10/lib/python3.10/site-packages/nonebot/internal/matcher/matcher.py", line 727, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "/USER_HOME_DIR/.cache/pypoetry/virtualenvs/zhenxun-bot-wZ02gYV3-py3.10/lib/python3.10/site-packages/nonebot/internal/matcher/matcher.py", line 702, in simple_run
    await handler(
  File "/USER_HOME_DIR/.cache/pypoetry/virtualenvs/zhenxun-bot-wZ02gYV3-py3.10/lib/python3.10/site-packages/nonebot/dependencies/__init__.py", line 108, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "/USER_HOME_DIR/zhenxun_bot/extensive_plugin/zhenxun_plugins_TZseries/TZdajie.py", line 110, in _
    q = await GroupInfoUser.get_or_none(user_qq=qq, group_id=group)
  File "/USER_HOME_DIR/.cache/pypoetry/virtualenvs/zhenxun-bot-wZ02gYV3-py3.10/lib/python3.10/site-packages/tortoise/queryset.py", line 1000, in __await__
    self._make_query()
  File "/USER_HOME_DIR/.cache/pypoetry/virtualenvs/zhenxun-bot-wZ02gYV3-py3.10/lib/python3.10/site-packages/tortoise/queryset.py", line 962, in _make_query
    self.resolve_filters(
  File "/USER_HOME_DIR/.cache/pypoetry/virtualenvs/zhenxun-bot-wZ02gYV3-py3.10/lib/python3.10/site-packages/tortoise/queryset.py", line 134, in resolve_filters
    modifier &= node.resolve(model, model._meta.basetable)
  File "/USER_HOME_DIR/.cache/pypoetry/virtualenvs/zhenxun-bot-wZ02gYV3-py3.10/lib/python3.10/site-packages/tortoise/expressions.py", line 359, in resolve
    return self._resolve_kwargs(model, table)
  File "/USER_HOME_DIR/.cache/pypoetry/virtualenvs/zhenxun-bot-wZ02gYV3-py3.10/lib/python3.10/site-packages/tortoise/expressions.py", line 317, in _resolve_kwargs
    key, value = self._get_actual_filter_params(model, raw_key, raw_value)
  File "/USER_HOME_DIR/.cache/pypoetry/virtualenvs/zhenxun-bot-wZ02gYV3-py3.10/lib/python3.10/site-packages/tortoise/expressions.py", line 311, in _get_actual_filter_params
    raise FieldError(f"Unknown filter param '{key}'. Allowed base values are {allowed}")
tortoise.exceptions.FieldError: Unknown filter param 'user_qq'. Allowed base values are ['group_id', 'id', 'nickname', 'uid', 'user_id', 'user_join_time', 'user_name']
```

**Comment by dzs2204775435** [comment]
我也是这样

**Comment by Ra2-IFV** [comment]
> 我也是这样

Try https://github.com/Ra2-IFV/zhenxun_plugins_TZseries/commit/2b9f155907b5c9d166c0c7831846d25a53906077

**Comment by CCYellowStar** [comment]
我的表还是老版的

**Comment by Ra2-IFV** [comment]
> 我的表还是老版的

最新git版本已經換成新表了 而最新的release版本還是舊表
Merge的時候得注意一下.......

**Comment by Ra2-IFV** [comment]
#50
